python run_swag_no_trainer_from_scratch.py\
  --train_file "./data/train.json" \
  --validation_file "./data/valid.json" \
  --context_file "./data/context.json" \
  --tokenizer_name bert-base-chinese \
  --hidden_size 384 \
  --num_hidden_layers 6 \
  --num_attention_heads 6 \
  --max_position_embeddings 512 \
  --max_seq_length 512 \
  --per_device_train_batch_size 2 \
  --per_device_eval_batch_size 8 \
  --gradient_accumulation_steps 8 \
  --learning_rate 5e-5 \
  --weight_decay 0.01 \
  --lr_scheduler_type cosine \
  --num_warmup_steps 200 \
  --num_train_epochs 1 \
  --output_dir "./output/mc_bert_from_scratch" \
  --gradient_checkpointing